--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aericio/PCEEasyEnchants
build-by-default: true
branches:
- master
projects:
  PCEEasyEnchants:
    path: ""
    lint:
      phpstan: false
...
