name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      - name: wget PiggyCustomEnchants
        uses: wei/wget@v1
        with:
          args: -O vendor/PiggyCustomEnchants.phar https://poggit.pmmp.io/r/80438/PiggyCustomEnchants_dev-429.phar
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: phpstan.neon.dist